### ISSUE TITLE
Embedded schema in generated Python classes does expand schema reference

### ISSUE THREAD

**Issue by shahbaz-techprescient** [hchasestevens/avro2py#8]

**Comment by hchasestevens** [comment]
Steps I think need to be done to remedy this:
1. Get the schemas from every record
2. Traverse them to find any inline definitions (until exhausted)
3. Take all schemas and replace all inline definitions with references
4. When producing the schema for a record, start with the only-references version
5. Traverse that version, keeping track of what definitions have been inlined, and only in the first instance of encountering something, replace it with its only-references version
6. Repeat 5 until there are no undefined records
